// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_user from "./routes/api/user.ts";
import * as $index from "./routes/index.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $sign_in from "./routes/sign-in.tsx";
import * as $sign_up from "./routes/sign-up.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/user.ts": $api_user,
    "./routes/index.tsx": $index,
    "./routes/profile.tsx": $profile,
    "./routes/sign-in.tsx": $sign_in,
    "./routes/sign-up.tsx": $sign_up,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
